"""
agents/critic.py

Critic Agent for the Telecom Complaint Agentic AI system.

The Critic reviews the proposal generated by the Planner.

It checks:

    1. Evidence consistency
    2. Risk consistency
    3. Policy consistency
    4. Decision appropriateness
    5. Priority appropriateness
    6. Unsupported assumptions
    7. Whether the proposal needs replanning

Architecture:

    Diagnosis ──┐
                │
    Policy ─────┼──► Planner ──► Critic
                │                  │
    Risk ───────┘                  │
                                   │
                           ┌───────┴───────┐
                           ▼               ▼
                        ACCEPT           REJECT
                           │               │
                           ▼               ▼
                        Decision         Replan
"""


import json

from app.agents.high.llm.qwen import ask_qwen
from app.agents.high.retrieval.historical import (
    assess_complaint_multidimensional_impact,
)

# ============================================================
# CRITIC AGENT
# ============================================================

def critic_agent(state: dict) -> dict:
    """
    Review the Planner's proposed decision.

    The Critic does NOT create a new intervention plan.

    It only determines whether the Planner's proposal is
    acceptable or needs to be sent to the Replan node.
    """

    print()
    print("=" * 60)
    print("NODE: CRITIC AGENT")
    print("=" * 60)


    # ========================================================
    # 1. COMPLAINT INFORMATION & MULTIDIMENSIONAL IMPACT
    # ========================================================

    complaint_id = state.get(
        "complaint_id",
        "UNKNOWN"
    )

    state.get(
        "complaint_text",
        state.get("complaint", "UNKNOWN")
    )

    state.get(
        "domain",
        "UNKNOWN"
    )

    state.get(
        "problem_type",
        "UNKNOWN"
    )

    state.get(
        "issue_signature",
        "UNKNOWN"
    )

    severity = state.get(
        "severity",
        "UNKNOWN"
    )

    occurrences_last_30_days = state.get(
        "occurrences_last_30_days",
        0
    )

    customer_previous_complaints = state.get(
        "customer_previous_complaints",
        0
    )

    sentiment_score = state.get(
        "sentiment_score",
        0.0
    )

    # Multidimensional Impact Assessment
    impact_assessment = assess_complaint_multidimensional_impact(state)
    impact_assessment["impact_level"]
    impact_assessment["impact_summary"]
    impact_assessment["critical_triggers"]
    impact_assessment["affected_subscribers"]
    days_unresolved = impact_assessment["days_unresolved"]
    duration_hours = impact_assessment["duration_hours"]
    future_impact_days = state.get("future_impact_days", 5)


    # ========================================================
    # 2. DIAGNOSIS
    # ========================================================

    diagnosis = state.get(
        "diagnosis",
        "UNKNOWN"
    )

    root_cause = state.get(
        "root_cause",
        state.get("diagnosis_root_cause", "UNKNOWN")
    )

    diagnosis_confidence = state.get(
        "diagnosis_confidence",
        0.0
    )


    # ========================================================
    # 3. POLICY
    # ========================================================

    policy_status = state.get(
        "policy_status",
        "UNKNOWN"
    )

    policy_reason = state.get(
        "policy_reason",
        "UNKNOWN"
    )

    policy_confidence = state.get(
        "policy_confidence",
        0.0
    )


    # ========================================================
    # 4. RISK
    # ========================================================

    risk_level = state.get(
        "risk_level",
        "UNKNOWN"
    )

    risk_reason = state.get(
        "risk_reason",
        "UNKNOWN"
    )

    risk_confidence = state.get(
        "risk_confidence",
        0.0
    )


    # ========================================================
    # 5. PLANNER PROPOSAL
    # ========================================================

    proposed_decision = state.get(
        "proposed_decision",
        "UNKNOWN"
    )

    priority = state.get(
        "priority",
        "UNKNOWN"
    )

    proposed_action = state.get(
        "proposed_action",
        "UNKNOWN"
    )

    planner_reason = state.get(
        "planner_reason",
        "UNKNOWN"
    )

    planner_confidence = state.get(
        "planner_confidence",
        0.0
    )


    # ========================================================
    # 6. SYSTEM PROMPT
    # ========================================================

    system_prompt = """
You are the Critic Agent in a telecom customer complaint decision-making system.

Your job is to independently review and validate the intervention proposal created by the Planner Agent.
You are a QUALITY CONTROL agent. You must NOT automatically agree with the Planner.

VALIDATION RULES:

1. CRITICAL PRIORITY VALIDATION:
   - If the Planner assigned priority = "CRITICAL" for a larger area problem with physical infrastructure damage (e.g. damaged tower) requiring immediate HUMAN ON-SITE FIELD INTERVENTION / technician dispatch:
     -> You MUST ACCEPT the proposal:
        "critic_decision": "ACCEPT",
        "replan_required": false,
        "critic_reason": "CRITICAL priority is fully justified due to larger area service outage and physical infrastructure damage requiring immediate human on-site field intervention."
   - 7-DAY RULE: If the complaint has been ongoing / unresolved for 7 or more days (days_unresolved >= 7 or duration >= 168 hours):
     -> You MUST ACCEPT the CRITICAL priority proposal:
        "critic_decision": "ACCEPT",
        "replan_required": false,
        "critic_reason": "CRITICAL priority is fully justified as the issue has exceeded the maximum 7-day unresolved SLA threshold."
   - If the Planner assigned priority = "CRITICAL" for a routine localized issue that has NOT exceeded 7 days and does NOT involve physical area damage or emergency human intervention:
     -> You MUST REJECT the proposal:
        "critic_decision": "REJECT",
        "replan_required": true,
        "critic_reason": "Planner over-escalated priority to CRITICAL without larger area disruption, 7-day overdue status, or human field intervention needs."

2. HIGH PRIORITY VALIDATION:
   - If the Planner assigned priority = "HIGH", proposed_decision = "ESCALATE", and a concrete operational action for standard high-severity complaints:
     -> You MUST ACCEPT the proposal:
        "critic_decision": "ACCEPT",
        "replan_required": false,
        "critic_reason": "Proposal is conservative, evidence-grounded, matches HIGH risk and ELEVATED policy, and provides a clear operational action."

3. TECHNICAL ASSUMPTION CHECK:
   - Since root cause is UNKNOWN, reject any proposal that invents unsupported technical root causes.
   - Reject claims of specific external company policies not in evidence.

4. CRITIC OUTCOMES:
   - ACCEPT: critic_decision = "ACCEPT", replan_required = false
   - REJECT: critic_decision = "REJECT", replan_required = true

Return ONLY one JSON object.

Required format:
{
    "critic_decision": "ACCEPT",
    "critic_reason": "short evidence-based reason",
    "critic_confidence": 0.98,
    "replan_required": false
}
"""


    # ========================================================
    # 7. USER PROMPT
    # ========================================================

    user_prompt = f"""
Review the following Planner proposal.

============================================================
COMPLAINT
============================================================

Complaint ID:
{complaint_id}

Severity:
{severity}

Occurrences in Last 30 Days:
{occurrences_last_30_days}

Previous Customer Complaints:
{customer_previous_complaints}

Negative Sentiment Score:
{sentiment_score}

Days Unresolved / Open:
{days_unresolved}

Duration (Hours):
{duration_hours}

Estimated Future Impact (Days):
{future_impact_days}


============================================================
DIAGNOSIS AGENT
============================================================

Diagnosis:
{diagnosis}

Root Cause:
{root_cause}

Confidence:
{diagnosis_confidence}


============================================================
POLICY AGENT
============================================================

Policy Status:
{policy_status}

Policy Reason:
{policy_reason}

Confidence:
{policy_confidence}


============================================================
RISK AGENT
============================================================

Risk Level:
{risk_level}

Risk Reason:
{risk_reason}

Confidence:
{risk_confidence}


============================================================
PLANNER PROPOSAL
============================================================

Proposed Decision:
{proposed_decision}

Priority:
{priority}

Proposed Action:
{proposed_action}

Planner Reason:
{planner_reason}

Planner Confidence:
{planner_confidence}


============================================================
CRITIC TASK
============================================================

Determine whether the Planner proposal should be accepted.

Remember:

- Root cause is UNKNOWN.
- Do not invent technical information.
- Do not invent company policy.
- HIGH risk does not automatically mean CRITICAL.
- ESCALATE may be appropriate when evidence supports
  additional investigation.
- The Critic does not create a new plan.
- If rejected, explain what needs to be corrected.

Return ONLY the required JSON object.
"""


    # ========================================================
    # 8. CALL QWEN
    # ========================================================

    response = ask_qwen(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        max_tokens=700,
        temperature=0.0,
        structured=True
    )


    # ========================================================
    # 9. PARSE JSON
    # ========================================================

    try:

        critic_result = json.loads(response)

    except json.JSONDecodeError as e:

        print()
        print("❌ Critic returned invalid JSON.")

        print("Qwen response:")
        print(response)

        raise ValueError(
            "Critic Agent returned invalid JSON."
        ) from e


    # ========================================================
    # 10. REQUIRED FIELDS
    # ========================================================

    required_fields = [
        "critic_decision",
        "critic_reason",
        "critic_confidence",
        "replan_required"
    ]

    for field in required_fields:

        if field not in critic_result:

            raise ValueError(
                f"Critic response is missing "
                f"required field: {field}"
            )


    # ========================================================
    # 11. VALIDATE CRITIC DECISION
    # ========================================================

    allowed_decisions = {
        "ACCEPT",
        "REJECT"
    }

    if critic_result["critic_decision"] not in allowed_decisions:

        raise ValueError(
            "Invalid Critic decision: "
            f"{critic_result['critic_decision']}"
        )


    # ========================================================
    # 12. VALIDATE REPLAN FLAG
    # ========================================================

    if not isinstance(
        critic_result["replan_required"],
        bool
    ):

        raise ValueError(
            "replan_required must be true or false."
        )


    # ========================================================
    # 13. DISPLAY RESULT
    # ========================================================

    print()
    print("Critic result:")

    print(
        json.dumps(
            critic_result,
            indent=2
        )
    )


    # ========================================================
    # 14. RETURN STATE UPDATE
    # ========================================================

    return {

        "critic_decision":
            critic_result["critic_decision"],

        "critic_reason":
            critic_result["critic_reason"],

        "critic_confidence":
            critic_result["critic_confidence"],

        "replan_required":
            critic_result["replan_required"]
    }